// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebToTest.Data;

namespace WebToTest.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview.18572.1");

            modelBuilder.Entity("WebToTest.Data.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("City");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("State");

                    b.Property<string>("Telephone");

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "2909 Furman Street ",
                            City = "Cap-Santé",
                            DateOfBirth = new DateTime(1994, 9, 7, 19, 55, 0, 0, DateTimeKind.Unspecified),
                            Email = "Antonio.Walker@microsoft.com",
                            FirstName = "Kayla",
                            LastName = "Stewart",
                            State = "Arkansas",
                            Telephone = "sold"
                        },
                        new
                        {
                            Id = 2,
                            Address = "8833 Pennsylvania Avenue ",
                            City = "Turlock",
                            DateOfBirth = new DateTime(1942, 9, 27, 8, 21, 29, 0, DateTimeKind.Unspecified),
                            Email = "Mason.Long@gmail.com",
                            FirstName = "Tanner",
                            LastName = "Getzlaff",
                            State = "North Dakota",
                            Telephone = "synth"
                        },
                        new
                        {
                            Id = 3,
                            Address = "4199 34th Street ",
                            City = "Kitchener",
                            DateOfBirth = new DateTime(1976, 5, 14, 19, 39, 43, 0, DateTimeKind.Unspecified),
                            Email = "Gabrielle.Verstraete@rogers.ca",
                            FirstName = "Julia",
                            LastName = "Tellies",
                            State = "Nevada",
                            Telephone = "echo"
                        },
                        new
                        {
                            Id = 4,
                            Address = "6565 Olean Street ",
                            City = "Sunnyvale",
                            DateOfBirth = new DateTime(1919, 3, 27, 20, 58, 43, 0, DateTimeKind.Unspecified),
                            Email = "Michelle.Long@hotmail.com",
                            FirstName = "Olivia",
                            LastName = "Mitchell",
                            State = "Guam",
                            Telephone = "vice"
                        },
                        new
                        {
                            Id = 5,
                            Address = "7125 Paerdegat 15th Street ",
                            City = "Manor",
                            DateOfBirth = new DateTime(2017, 7, 11, 13, 58, 51, 0, DateTimeKind.Unspecified),
                            Email = "Isabel.Barnes@microsoft.com",
                            FirstName = "Rachel",
                            LastName = "Foster",
                            State = "Oregon",
                            Telephone = "ethical"
                        },
                        new
                        {
                            Id = 6,
                            Address = "4969 Sterling Place ",
                            City = "EurekaCounty seat",
                            DateOfBirth = new DateTime(1964, 8, 9, 3, 4, 54, 0, DateTimeKind.Unspecified),
                            Email = "Elizabeth.Main@gmx.com",
                            FirstName = "Thomas",
                            LastName = "Watson",
                            State = "Virginia",
                            Telephone = "work"
                        },
                        new
                        {
                            Id = 7,
                            Address = "8052 Stillwell Avenue ",
                            City = "Lakeport",
                            DateOfBirth = new DateTime(1905, 2, 14, 17, 35, 41, 0, DateTimeKind.Unspecified),
                            Email = "Evelyn.Wilson@shaw.ca",
                            FirstName = "Marissa",
                            LastName = "Brooks",
                            State = "Alaska",
                            Telephone = "artisan"
                        },
                        new
                        {
                            Id = 8,
                            Address = "3155 Danforth Street ",
                            City = "L'Assomption",
                            DateOfBirth = new DateTime(2010, 3, 24, 16, 4, 32, 0, DateTimeKind.Unspecified),
                            Email = "Paul.Morgan@att.com",
                            FirstName = "Savannah",
                            LastName = "Mitchell",
                            State = "Mississippi",
                            Telephone = "authentic"
                        },
                        new
                        {
                            Id = 9,
                            Address = "7910 Burnett Street ",
                            City = "Covina",
                            DateOfBirth = new DateTime(1949, 9, 20, 0, 32, 36, 0, DateTimeKind.Unspecified),
                            Email = "Jose.Ramirez@att.com",
                            FirstName = "Aaliyah",
                            LastName = "Green",
                            State = "Montana",
                            Telephone = "thing"
                        },
                        new
                        {
                            Id = 10,
                            Address = "1942 Midwood Street ",
                            City = "Blue Lake",
                            DateOfBirth = new DateTime(1961, 11, 14, 19, 45, 16, 0, DateTimeKind.Unspecified),
                            Email = "Chloe.Turner@gmail.com",
                            FirstName = "Devin",
                            LastName = "Main",
                            State = "Louisiana",
                            Telephone = "sriracha"
                        },
                        new
                        {
                            Id = 11,
                            Address = "4132 Walker Court ",
                            City = "Prince Rupert",
                            DateOfBirth = new DateTime(1958, 3, 7, 5, 44, 26, 0, DateTimeKind.Unspecified),
                            Email = "Leslie.Bennett@gmx.com",
                            FirstName = "Jeremy",
                            LastName = "Martin",
                            State = "Pennsylvania",
                            Telephone = "beer"
                        },
                        new
                        {
                            Id = 12,
                            Address = "8045 Ocean Court ",
                            City = "Grand Terrace",
                            DateOfBirth = new DateTime(1968, 9, 13, 16, 38, 6, 0, DateTimeKind.Unspecified),
                            Email = "Leslie.Perry@microsoft.com",
                            FirstName = "Taylor",
                            LastName = "Olsen",
                            State = "Indiana",
                            Telephone = "VHS"
                        },
                        new
                        {
                            Id = 13,
                            Address = "8913 Glenwood Road ",
                            City = "Westway",
                            DateOfBirth = new DateTime(1972, 11, 10, 3, 45, 36, 0, DateTimeKind.Unspecified),
                            Email = "Gavin.Wright@shaw.ca",
                            FirstName = "Rachel",
                            LastName = "Brandzin",
                            State = "Delaware",
                            Telephone = "Brooklyn"
                        },
                        new
                        {
                            Id = 14,
                            Address = "4976 Water Street ",
                            City = "Petaluma",
                            DateOfBirth = new DateTime(1918, 12, 31, 11, 14, 50, 0, DateTimeKind.Unspecified),
                            Email = "Kaitlyn.Morgan@hotmail.com",
                            FirstName = "Chloe",
                            LastName = "Ratzlaff",
                            State = "Minnesota",
                            Telephone = "future"
                        },
                        new
                        {
                            Id = 15,
                            Address = "911 Division Avenue ",
                            City = "Blossom",
                            DateOfBirth = new DateTime(1985, 8, 14, 1, 18, 3, 0, DateTimeKind.Unspecified),
                            Email = "Abigail.Scott@shaw.ca",
                            FirstName = "Mason",
                            LastName = "Lewis",
                            State = "Tennessee",
                            Telephone = "company"
                        },
                        new
                        {
                            Id = 16,
                            Address = "4395 Kane Street ",
                            City = "Pittsburg",
                            DateOfBirth = new DateTime(1962, 6, 18, 9, 28, 14, 0, DateTimeKind.Unspecified),
                            Email = "Shelby.Ramirez@telus.net",
                            FirstName = "Hailey",
                            LastName = "Daeninck",
                            State = "Wyoming",
                            Telephone = "denim"
                        },
                        new
                        {
                            Id = 17,
                            Address = "2549 Paerdegat 12th Street ",
                            City = "Shelbyville",
                            DateOfBirth = new DateTime(1972, 8, 1, 19, 50, 13, 0, DateTimeKind.Unspecified),
                            Email = "Makayla.Hill@shaw.ca",
                            FirstName = "Sophia",
                            LastName = "Thompson",
                            State = "Colorado",
                            Telephone = "PBR"
                        },
                        new
                        {
                            Id = 18,
                            Address = "9963 Logan Street ",
                            City = "Ottawa",
                            DateOfBirth = new DateTime(1968, 3, 4, 21, 3, 56, 0, DateTimeKind.Unspecified),
                            Email = "Elizabeth.Ward@microsoft.com",
                            FirstName = "Hannah",
                            LastName = "Getzlaff",
                            State = "South Dakota",
                            Telephone = "williamsburg"
                        },
                        new
                        {
                            Id = 19,
                            Address = "4222 Myrtle Avenue ",
                            City = "Waterville",
                            DateOfBirth = new DateTime(1907, 11, 10, 9, 46, 47, 0, DateTimeKind.Unspecified),
                            Email = "Lauren.Gonzalez@rogers.ca",
                            FirstName = "Alexa",
                            LastName = "Long",
                            State = "Missouri",
                            Telephone = "park"
                        },
                        new
                        {
                            Id = 20,
                            Address = "8695 Grove Place ",
                            City = "Chibougamau",
                            DateOfBirth = new DateTime(1943, 7, 21, 10, 40, 20, 0, DateTimeKind.Unspecified),
                            Email = "Elizabeth.Anderson@gmx.com",
                            FirstName = "Angel",
                            LastName = "Wood",
                            State = "Connecticut",
                            Telephone = "Umami"
                        },
                        new
                        {
                            Id = 21,
                            Address = "2577 Bancroft Place ",
                            City = "Canadian",
                            DateOfBirth = new DateTime(1912, 9, 28, 0, 43, 20, 0, DateTimeKind.Unspecified),
                            Email = "Jeremy.Carter@live.com",
                            FirstName = "Carlos",
                            LastName = "Richardson",
                            State = "Mississippi",
                            Telephone = "sriracha"
                        },
                        new
                        {
                            Id = 22,
                            Address = "1602 Aitken Place ",
                            City = "Marina",
                            DateOfBirth = new DateTime(1900, 5, 30, 13, 57, 43, 0, DateTimeKind.Unspecified),
                            Email = "Luis.Murphy@hotmail.com",
                            FirstName = "Nathan",
                            LastName = "Hernandez",
                            State = "Washington",
                            Telephone = "carles"
                        },
                        new
                        {
                            Id = 23,
                            Address = "4684 Trucklemans Lane ",
                            City = "Elmira",
                            DateOfBirth = new DateTime(1954, 11, 2, 22, 45, 13, 0, DateTimeKind.Unspecified),
                            Email = "Kelsey.Jenkins@rogers.ca",
                            FirstName = "Gabriela",
                            LastName = "Olsen",
                            State = "Illinois",
                            Telephone = "williamsburg"
                        },
                        new
                        {
                            Id = 24,
                            Address = "8039 Dakota Place ",
                            City = "Moorpark",
                            DateOfBirth = new DateTime(2017, 4, 12, 1, 33, 2, 0, DateTimeKind.Unspecified),
                            Email = "Paige.Thomas@microsoft.com",
                            FirstName = "Devin",
                            LastName = "Verstraete",
                            State = "American Samoa",
                            Telephone = "fap"
                        },
                        new
                        {
                            Id = 25,
                            Address = "8334 Seacoast Terrace ",
                            City = "Olney",
                            DateOfBirth = new DateTime(1978, 6, 1, 18, 35, 29, 0, DateTimeKind.Unspecified),
                            Email = "Ashley.Bell@live.com",
                            FirstName = "Steven",
                            LastName = "Perry",
                            State = "Vermont",
                            Telephone = "child"
                        },
                        new
                        {
                            Id = 26,
                            Address = "6138 Oxford Walk ",
                            City = "Bartonville",
                            DateOfBirth = new DateTime(1988, 2, 4, 11, 29, 43, 0, DateTimeKind.Unspecified),
                            Email = "Alexandria.Brandzin@hotmail.com",
                            FirstName = "Angel",
                            LastName = "Hughes",
                            State = "District of Columbia",
                            Telephone = "american"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
